spring.application.name=clinic_system


spring.datasource.url=jdbc:postgresql://localhost:5432/clinic_system
spring.datasource.username=postgres
spring.datasource.password=1959

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8084